apiVersion: v1
kind: Pod
metadata:
  name: "sample"
  labels:
    app: "sample"
spec:
  containers:
    - name: "golang"
      image: "bumbaruflaviusgabriel/golanggraph:1.0"
      ports:
        - containerPort: 8081