apiVersion: v1
kind: Service

metadata:
  name: postgres
  namespace: newnamespace

spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5437
    targetPort: 5432


